### ISSUE TITLE
about.html - change text in about

### ISSUE THREAD

**Issue by hellolulu** [ibcol/IBCOL-2023#2]
Current: HKBCOL combines the practicality of a traditional case competitions with the open-ended problem-solving culture of hack-a-thons. As a team of up to 6 students, competitors will submit their case as using an academic conference style white-paper along with a pitch and presentation deck.

Updated: HKBCOL combines the practicality of a traditional case competitions with the open-ended problem-solving culture of hack-a-thons. As a team of up to 6 students, competitors will submit their case as using an academic conference style white-paper along with a 3-min video presentation and a poster board.

**Comment by ninjapanda** [comment]
Issue entered into the incorrect repository, sorry!
